version: 2
updates:
  - package-ecosystem: "nuget"
    directories:
      - "/cli/TimeTracker.Cli"
      - "/libs/TimeTracker.Core"
      - "/tests/TimeTracker.Core.Tests"
    schedule:
      interval: "weekly"
    groups:
      nuget-minor-patch:
        update-types: ["minor", "patch"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns: ["*"]
