version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/cli/TimeTracker.Cli"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/libs/TimeTracker.Core"
    schedule:
      interval: "weekly"
